[package]
name = "entity"
version = "0.1.0"
authors = ["Dr. David Alexander Kunz <kunz.david.alexander@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-entity = { path = "./derive-entity" }
